### PR TITLE
Removed module level call to ``get_media_base_form()``

### LINKED ISSUE #147: BaseMediaForm cannot be subclassed
### Issue Summary

I attempted a customization along the lines of #64. My first approach was to subclass the existing BaseMediaForm so I could inherit the existing ``__init__`` logic and ``permission_policy`` and focus solely on modifying the widgets. However, this lead to errors since ``get_base_form()`` is called at the module level:

https://github.com/torchbox/wagtailmedia/blob/4d0efb921833325652cd2afe0a6bbd4ef9763a61/src/wagtailmedia/forms.py#L48

The resulting error:

```
AttributeError: partially initialized module 'my_app.forms' has no attribute 'CustomMediaForm' (most likely due to a circular import)
```

Any reason the ``get_base_form()`` call cannot happen inside ``get_media_form()``?

Happy to submit a PR if this change is acceptable. Thanks!

### PR DESCRIPTION
**Pull request by jsma**
This caused import issues for projects that subclassed ``BaseMediaForm``.
Updated tests to rely on overriding settings instead of mocking the return value.
Fixed tox config for dj32, which was accidentally only testing Django 3.1.x (the bug was introduced in 5e2f95eb6a).

Fixes #147

### CODE REVIEW

**Review by zerolab — APPROVED** [review]
LGTM
Thank you for the fix @jsma!
